### ISSUE TITLE
legacy: remove bibdocfile dependency

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-redirector#2]
All the dependencies are concentrated in the [goto_plugin_cern_hr_documents](https://github.com/inveniosoftware/invenio-redirector/blob/master/invenio_redirector/redirect_methods/goto_plugin_cern_hr_documents.py#L81) plugin.
Someone use it? Any idea how to remove bibdocfile dependency?

**Comment by kaplun** [comment]
This plugin should sit into the CDS repo, it does not have any use within Invenio (unless as a show case of a complex example).

@ludmilamarian, @kasioumis, @egabancho ?

**Comment by ludmilamarian** [comment]
I agree.. it can sit in the CDS overlay. I think it's in Invenio just as an example.

**Comment by hachreak** [comment]
I forgot another module that it uses legacy code..
What about the [goto_plugin_latest_record.py](https://github.com/inveniosoftware/invenio-redirector/blob/master/invenio_redirector/redirect_methods/goto_plugin_latest_record.py) plugin?
